spring:
  application:
    name: niwe_erp

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:postgresql://localhost:5434/niwe_erp_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: postgres
    password: npf2020.
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: Africa/Kigali
    open-in-view: true

  flyway:
    enabled: false
    schemas: public
    baseline-on-migrate: true
    baseline-version: 0
    locations:
      - classpath:db/migration/common
      - classpath:db/migration/dev

  messages:
    basename: messages
    encoding: UTF-8

server:
  servlet:
    context-path: /niwe_erp
  port: 9391
  tomcat:
    max-swallow-size: 100MB

logging:
  level:
    com.zaxxer.hikari.HikariDataSource: DEBUG
    com.zaxxer.hikari: TRACE
    org.springframework.web.reactive.function.client.WebClient: DEBUG
    reactor.netty.http.client: DEBUG
    root: INFO
    com.niwe: DEBUG
  file:
    name: logs/app.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
